/******************************************************************************/
//
// This file was generated by OSAcfg_Tool utility.
// Do not modify it to prevent data loss on next editing.
//
// PROJECT NAME: Pisca_Led
//
// PLATFORM:     mikroC for PIC18
//
/******************************************************************************/


#ifndef _OSACFG_H
#define _OSACFG_H

//------------------------------------------------------------------------------
// SYSTEM
//------------------------------------------------------------------------------

#define OS_TASKS                4   // Number of tasks that can be active at one time
#define OS_PRIORITY_LEVEL  OS_PRIORITY_NORMAL 

//------------------------------------------------------------------------------
// ENABLE CONSTANTS
//------------------------------------------------------------------------------

#define OS_ENABLE_TTIMERS           // Enable task timers (OS_Delay and OS_xxx_Wait_TO)
#define OS_USE_INLINE_TIMER         // Make OS_Timer service as in-line function


//------------------------------------------------------------------------------
// TYPES
//------------------------------------------------------------------------------

#define OS_TIMER_SIZE           4   // Size of all system timers (1, 2 or 4)
#define OS_TTIMER_SIZE          4   // Size of task timers (1, 2 or 4)


#define OS_SMSG_TYPE           unsigned int


#endif
